[tasmota]
; Reset global build / unbuild compile time flags for ALL Tasmota / Tasmota32 [env]
; since custom env are designed to enable options individual
build_unflags               =
build_flags                 =

; my own custom variant
[env:tasmota32s3-lvgl-thermostat]
extends                     = env:tasmota32_base
board                       = esp32s3ser-qio_opi_120
#board                       = esp32s3-qio_opi
#board_build.f_cpu           = 240000000L
#board_build.f_flash         = 80000000L
#board_build.f_flash         = 120000000L
#board_build.f_boot          = 120000000L
#board_build.boot            = qio
build_unflags           = -Os
build_flags             = ${env:tasmota32_base.build_flags}
                          -DFIRMWARE_LVGL_THERMOSTAT
                          -O2
                          -DUSE_BERRY_DEBUG
                          #-DARDUINO_RUNNING_CORE=1
                          #-DARDUINO_EVENT_RUNNING_CORE=1

custom_sdkconfig        = CONFIG_FREERTOS_HZ=1000
                          CONFIG_ESP_DEFAULT_CPU_FREQ_MHZ_240=y
                          CONFIG_ESPTOOLPY_FLASHMODE_QIO=y
                          CONFIG_ESPTOOLPY_FLASHFREQ_120M=y
                          CONFIG_SPIRAM_MODE_OCT=y
                          '# CONFIG_SPIRAM_MODE_QUAD is not set'
                          CONFIG_IDF_EXPERIMENTAL_FEATURES=y
                          CONFIG_SPIRAM_SPEED=120
                          CONFIG_SPIRAM_SPEED_120M=y
                          '# CONFIG_SPIRAM_SPEED_80M is not set'
                          '# CONFIG_SPIRAM_SPEED_40M is not set'
                          CONFIG_SPIRAM_FETCH_INSTRUCTIONS=y
                          CONFIG_SPIRAM_RODATA=y
                          CONFIG_SOC_SPIRAM_XIP_SUPPORTED=y
                          #CONFIG_ESP32S3_DATA_CACHE_LINE_64B=y
                          #'# CONFIG_ESP32S3_DATA_CACHE_LINE_32B is not set'
                          CONFIG_ESP32_PTHREAD_TASK_STACK_SIZE_DEFAULT=3072
                          CONFIG_COMPILER_OPTIMIZATION_PERF=y
                          '# CONFIG_COMPILER_OPTIMIZATION_SIZE is not set'
                          '# CONFIG_BT_ENABLED is not set'
                          CONFIG_LOG_COLORS=y
                          #CONFIG_ARDUINO_ISR_IRAM=y
                          CONFIG_ESP32_WIFI_IRAM_OPT=y
                          CONFIG_ESP32_WIFI_RX_IRAM_OPT=y
                          CONFIG_ESP_WIFI_RX_IRAM_OPT=y
                          CONFIG_ESP_EVENT_POST_FROM_IRAM_ISR=y
                          CONFIG_ESP_EVENT_POST_FROM_ISR=y
                          CONFIG_LCD_RGB_ISR_IRAM_SAFE=y
                          CONFIG_LCD_PANEL_IO_FORMAT_BUF_SIZE=32
                          #CONFIG_ESP32_WIFI_IRAM_OPT=y
                          #CONFIG_ESP_WIFI_EXTRA_IRAM_OPT=y
                          #CONFIG_LWIP_IRAM_OPTIMIZATION=y
                          CONFIG_PERIPH_CTRL_FUNC_IN_IRAM=y
                          CONFIG_POST_EVENTS_FROM_IRAM_ISR=y
                          CONFIG_SPI_MASTER_ISR_IN_IRAM=y
                          CONFIG_SPI_SLAVE_ISR_IN_IRAM=y
                          CONFIG_SPIRAM_BOOT_INIT=y
                          CONFIG_SYSTEM_EVENT_TASK_STACK_SIZE=2304
                          CONFIG_ESP_SYSTEM_EVENT_TASK_STACK_SIZE=2304
                          CONFIG_ESP_IPC_TASK_STACK_SIZE=1280
                          CONFIG_IPC_TASK_STACK_SIZE=1280
                          CONFIG_ESP_TASK_WDT_CHECK_IDLE_TASK_CPU1=y
                          '# CONFIG_FREERTOS_PLACE_FUNCTIONS_INTO_FLASH is not set'      # ???
                          CONFIG_GDMA_CTRL_FUNC_IN_IRAM=y
                          CONFIG_GDMA_ISR_IRAM_SAFE=y
                          CONFIG_HAL_SPI_MASTER_FUNC_IN_IRAM=y
                          CONFIG_HAL_SPI_SLAVE_FUNC_IN_IRAM=y
                          CONFIG_LCD_RGB_ISR_IRAM_SAFE=y
                          CONFIG_SPI_FLASH_UNDER_HIGH_FREQ=y

                          CONFIG_SPIRAM_ALLOW_STACK_EXTERNAL_MEMORY=y
                          CONFIG_SPIRAM_CLK_IO=30
                          CONFIG_SPIRAM_CS_IO=26
                          '# CONFIG_SPIRAM_XIP_FROM_PSRAM is not set'
                          CONFIG_SPIRAM_USE_MALLOC=y
                          CONFIG_SPIRAM_MEMTEST=y
                          CONFIG_SPIRAM_MALLOC_ALWAYSINTERNAL=16384
                          '# CONFIG_SPIRAM_TRY_ALLOCATE_WIFI_LWIP is not set'
                          CONFIG_SPIRAM_MALLOC_RESERVE_INTERNAL=32768

                          CONFIG_ESP32S3_SPIRAM_SUPPORT=y
                          CONFIG_DEFAULT_PSRAM_CLK_IO=30
                          CONFIG_DEFAULT_PSRAM_CS_IO=26
                          '# CONFIG_ESP32S3_DEFAULT_CPU_FREQ_80 is not set'
                          '# CONFIG_ESP32S3_DEFAULT_CPU_FREQ_160 is not set'
                          CONFIG_ESP32S3_DEFAULT_CPU_FREQ_240=y
                          CONFIG_ESP32S3_DEFAULT_CPU_FREQ_MHZ=240


lib_extra_dirs          = lib/libesp32, lib/libesp32_lvgl, lib/lib_basic, lib/lib_i2c, lib/lib_rf, lib/lib_div, lib/lib_ssl, lib/lib_display
lib_ignore              = ${env:tasmota32_base.lib_ignore}
                          Micro-RTSP
                          NeoPixelBus
                          BlueRobotics_MS5837_Library
                          MPU_accel
                          LoRa
                          RA8876
                          IRremoteESP8266
                          TasmotaModbus
                          ESP Mail Client
                          ESPFtpServer
                          Ethernet
                          # BearSSL
                          OpenTherm
                          Mutichannel_Gas_Sensor
                          AT24C256_512
                          Adafruit_SGP40
                          Adafruit-GFX-Library
                          A4988_Stepper
                          Sensirion_Core
                          RadioLib
                          esp-knx-ip

[env:tasmota-rangeextender]
build_flags                 = ${env.build_flags}
                              -DFIRMWARE_RANGE_EXTENDER
                              -DPIO_FRAMEWORK_ARDUINO_LWIP2_HIGHER_BANDWIDTH
                              -DUSE_WIFI_RANGE_EXTENDER
                              -DUSE_WIFI_RANGE_EXTENDER_NAPT
                              -DOTA_URL='""'

[env:tasmota32-rangeextender]
extends                     = env:tasmota32_base
build_flags                 = ${env:tasmota32_base.build_flags}
                              -DFIRMWARE_TASMOTA32
                              -DUSE_WIFI_RANGE_EXTENDER
                              -DUSE_WIFI_RANGE_EXTENDER_NAPT
                              -DOTA_URL='""'

; remove PSRAM support -> avoid "blinking" of GPIO 16/17 at boot
[env:tasmota32-nopsram]
extends                     = env:tasmota32
build_unflags               = ${env:tasmota32_base.build_unflags}
                              -DBOARD_HAS_PSRAM
build_flags                 = ${env:tasmota32_base.build_flags}
                              -DFIRMWARE_TASMOTA32
                              -DDISABLE_PSRAMCHECK
                              -DCODE_IMAGE_STR='"tasmota32-nopsram"'
                              -DOTA_URL='""'

[env:tasmota32s3-file]
extends                     = env:tasmota32_base
board                       = esp32s3-qio_qspi
board_build.f_cpu           = 240000000L
board_build.f_flash         = 80000000L
build_flags                 = ${env:tasmota32_base.build_flags}
                              -DFIRMWARE_TASMOTA32
                              -DOTA_URL='"http://ota.tasmota.com/tasmota32/release/tasmota32s3.bin"'
; Example for custom file upload in Tasmota Filesystem
custom_files_upload         = ${env:tasmota32_base.custom_files_upload}
                              tasmota/berry/modules/Partition_Wizard.tapp
                              https://github.com/tasmota/autoconf/raw/main/esp32s3/DevKitC-1.autoconf

[env:tasmota32s3-qio_opi-all]
extends                     = env:tasmota32_base
board                       = esp32s3-qio_opi
board_build.f_cpu           = 240000000L
board_build.f_flash         = 80000000L
build_flags                 = ${env:tasmota32_base.build_flags}
                              -DUSE_WEBCAM
                              -DUSE_BERRY_ULP
                              -DFIRMWARE_LVGL
                              -DUSE_LVGL_OPENHASP
                              -DOTA_URL='""'

[env:tasmota32s3-qio_opi_120]
; device needs >= 8MB Flash!!
extends                     = env:tasmota32_base
board                       = esp32s3-qio_opi_120
board_build.partitions      = partitions/esp32_partition_app3904k_fs3392k.csv
build_flags                 = ${env:tasmota32_base.build_flags}
                              -DUSE_BERRY_ULP
                              -DFIRMWARE_LVGL
                              -DUSE_LVGL_OPENHASP
                              -DOTA_URL='""'

[env:tasmota32s3-opi_opi]
extends                     = env:tasmota32_base
board                       = esp32s3-opi_opi
board_build.f_cpu           = 240000000L
board_build.f_flash         = 80000000L
build_flags                 = ${env:tasmota32_base.build_flags}
                              -DUSE_BERRY_ULP
                              -DFIRMWARE_LVGL
                              -DUSE_LVGL_OPENHASP
                              -DOTA_URL='""'

[env:tasmota32c3-bluetooth]
extends                     = env:tasmota32_base
board                       = esp32c3
build_flags                 = ${env:tasmota32_base.build_flags}
                              -DFIRMWARE_BLUETOOTH
;                              -DUSE_EQ3_ESP32
                              -DOTA_URL='""'
lib_extra_dirs              = lib/libesp32, lib/libesp32_div, lib/lib_basic, lib/lib_i2c, lib/lib_rf, lib/lib_div, lib/lib_ssl, lib/lib_display, lib/lib_audio
lib_ignore                  = Micro-RTSP

[env:tasmota32s3-bluetooth]
extends                     = env:tasmota32_base
board                       = esp32s3-qio_qspi
build_flags                 = ${env:tasmota32_base.build_flags}
                              -DFIRMWARE_BLUETOOTH
                              -DOTA_URL='""'
lib_extra_dirs              = lib/libesp32, lib/libesp32_div, lib/lib_basic, lib/lib_ssl, lib/lib_i2c
lib_ignore                  = Micro-RTSP

[env:tasmota32-mi32]
extends                     = env:tasmota32_base
build_flags                 = ${env:tasmota32_base.build_flags}
                              -DFIRMWARE_BLUETOOTH
                              -DUSE_MI_EXT_GUI
                              -DCONFIG_BT_NIMBLE_NVS_PERSIST=y
                              -DOTA_URL='""'
lib_extra_dirs              = lib/libesp32, lib/libesp32_div, lib/lib_basic, lib/lib_i2c, lib/lib_div, lib/lib_ssl
lib_ignore                  = Micro-RTSP

[env:tasmota32c3-mi32]
extends                     = env:tasmota32_base
board                       = esp32c3
build_flags                 = ${env:tasmota32_base.build_flags}
                              -DFIRMWARE_BLUETOOTH
                              -DUSE_MI_EXT_GUI
                              -DCONFIG_BT_NIMBLE_NVS_PERSIST=y
                              -DOTA_URL='""'
lib_extra_dirs              = lib/libesp32, lib/libesp32_div, lib/lib_basic, lib/lib_i2c, lib/lib_div, lib/lib_ssl
lib_ignore                  = Micro-RTSP

[env:tasmota32s3-mi32]
extends                     = env:tasmota32_base
board                       = esp32s3-qio_qspi
build_flags                 = ${env:tasmota32_base.build_flags}
                              -DFIRMWARE_BLUETOOTH
                              -DUSE_MI_EXT_GUI
                              -DCONFIG_BT_NIMBLE_NVS_PERSIST=y
                              -DOTA_URL='""'
lib_extra_dirs              = lib/libesp32, lib/libesp32_div, lib/lib_basic, lib/lib_i2c, lib/lib_div, lib/lib_ssl
lib_ignore                  = Micro-RTSP

[env:tasmota32c6-mi32]
extends                     = env:tasmota32_base
board                       = esp32c6
build_flags                 = ${env:tasmota32_base.build_flags}
                              -DFIRMWARE_BLUETOOTH
                              -DUSE_MI_EXT_GUI
                              -DCONFIG_BT_NIMBLE_NVS_PERSIST=y
                              -DOTA_URL='""'

; *** Debug version used for PlatformIO Home Project Inspection
[env:tasmota-debug]
build_type                  = debug
build_unflags               = ${env.build_unflags}
check_tool                  = cppcheck
                              ;clangtidy
check_skip_packages         = yes
build_flags                 = ${env.build_flags}
;                              -Wstack-usage=300
                              -DOTA_URL='""'

[env:tasmota32-debug]
extends                     = env:tasmota32_base
build_type                  = debug
build_unflags               = ${env:tasmota32_base.build_unflags}
build_flags                 = ${env:tasmota32_base.build_flags}
                              -DOTA_URL='""'
check_tool                  = cppcheck
                              ;clangtidy
check_skip_packages         = yes


; *** JTAG Debug version, needs esp-prog or FT2232H or FT232H
; *** Install howto for Windows https://community.platformio.org/t/esp32-pio-unified-debugger/4541/20

[env:tasmota32-ocd]
build_type                  = debug
extends                     = env:tasmota32_base
board                       = esp32
debug_tool                  = esp-prog
upload_protocol             = esp-prog
debug_init_break            = tbreak setup
build_unflags               = ${env:tasmota32_base.build_unflags}
build_flags                 = ${env:tasmota32_base.build_flags}
                              -DOTA_URL='""'

[env:tasmota32solo1-ocd]
build_type                  = debug
extends                     = env:tasmota32solo1
board                       = esp32-solo1
debug_tool                  = esp-prog
upload_protocol             = esp-prog
debug_init_break            = tbreak setup
build_unflags               = ${env:tasmota32_base.build_unflags}
build_flags                 = ${env:tasmota32_base.build_flags}
                              -DOTA_URL='""'
custom_sdkconfig            = CONFIG_FREERTOS_UNICORE=y

[env:tasmota32s2-ocd]
build_type                  = debug
extends                     = env:tasmota32_base
board                       = esp32s2
debug_tool                  = esp-prog
upload_protocol             = esp-prog
debug_init_break            = tbreak setup
build_unflags               = ${env:tasmota32_base.build_unflags}
build_flags                 = ${env:tasmota32_base.build_flags}
                              -DOTA_URL='""'

; *** JTAG Debug versions (only C3/S3), uses inbuilt CDC/jtag. No extra jtag hardware required!

[env:tasmota32s3-ocd]
build_type                  = debug
extends                     = env:tasmota32s3
board                       = esp32s3-qio_opi
debug_tool                  = esp-builtin
upload_protocol             = esp-builtin
debug_init_break            = tbreak setup
build_unflags               = ${env:tasmota32_base.build_unflags}
build_flags                 = ${env:tasmota32_base.build_flags}
                              -DOTA_URL='""'

[env:tasmota32c3-ocd]
build_type                  = debug
extends                     = env:tasmota32c3
board                       = esp32c3
debug_tool                  = esp-builtin
upload_protocol             = esp-builtin
debug_init_break            = tbreak setup
build_unflags               = ${env:tasmota32c3.build_unflags}
build_flags                 = ${env:tasmota32c3.build_flags}
                              -DOTA_URL='""'
